name: ci

on:
  #push:
    #paths:
      #- ".github/workflows/ci.yml"
      #- src/**
      #- scripts/mktag.sh
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  server-docker:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
    outputs:
      image: ${{steps.img.outputs.name}}@${{steps.build.outputs.digest}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest release publish time
        id: fetch_release
        run: |
          curl -s https://api.github.com/repos/NekoUwUGamerfnf/Zanieon-Frontier-Defense/releases/latest > release.json
          jq -r .published_at release.json > published_at.txt
          echo "Published at: $(cat published_at.txt)"

      - name: Check if published within the last hour
        id: check_time
        run: |
          PUBLISHED_AT=$(cat published_at.txt)
          # Convert published time and now to Unix timestamps
          PUBLISHED_TS=$(date -d "$PUBLISHED_AT" +%s)
          NOW_TS=$(date -u +%s)

          DIFF=$((NOW_TS - PUBLISHED_TS))

          echo "Now: $(date -u)"
          echo "Published: $PUBLISHED_AT"
          echo "Time difference: $DIFF seconds"

          if [ "$DIFF" -le 3600 ]; then
            echo "recent=true" >> $GITHUB_OUTPUT
            echo "A release was published within the last hour."
          else
            echo "recent=false" >> $GITHUB_OUTPUT
            echo "No recent release in the last hour."
            exit 1
          fi

      - id: img
        name: Generate image name
        run: name="$(echo "ghcr.io/${{github.repository_owner}}/frontier-defense-dedicated" | tr "[:upper:]" "[:lower:]")"; echo "${name}"; echo "name=${name}" >> $GITHUB_OUTPUT

      - id: tags
        name: Generate tags
        run: ./scripts/mktag.sh ${{steps.img.outputs.name}} stable-git stable

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - id: build
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src
          push: true
          tags: ${{steps.tags.outputs.tags}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.created=${{steps.tags.outputs.rfc3339}}
            org.opencontainers.image.authors=discord:pg9182#8484
            org.opencontainers.image.url=https://github.com/${{github.repository}}
            org.opencontainers.image.documentation=https://github.com/${{github.repository}}
            org.opencontainers.image.source=https://github.com/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.vendor=${{github.repository_owner}}
            org.opencontainers.image.licenses=Zlib AND MIT
            org.opencontainers.image.description=northstar-dedicated v${{steps.tags.outputs.ever}} @ ${{steps.tags.outputs.git}} (Titanfall v${{steps.tags.outputs.tfver}} / Northstar v${{steps.tags.outputs.nsver}})
            io.github.pg9182.northstar-dedicated.northstar.version=${{steps.tags.outputs.nsver}}
            io.github.pg9182.northstar-dedicated.titanfall.version=${{steps.tags.outputs.tfver}}
            io.github.pg9182.northstar-dedicated.entrypoint.compat=${{steps.tags.outputs.ever}}
            io.github.pg9182.northstar-dedicated.entrypoint.version=${{github.sha}}
